version: "3.7"

services:
  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/etc/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root

  webserver:
    image: nginx:alpine
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
    depends_on: 
      - php-fpm

  php-fpm:
    build: php-fpm
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      - ./php-fpm/sessions:/var/lib/php/sessions
      - ./php-fpm/profiler-reports:/profiler-reports

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - 3306:80
    links:
      - mysql:db